### ISSUE TITLE
Styling to the main page

### ISSUE THREAD

**Issue by Code-Aditya-14** [Code-Aditya-14/CP-Academy#2]
Add proper styling to the tables and others in that main page i.e. add stylings in [style-main](https://github.com/Code-Aditya-14/CP-Academy/blob/main/style-main.css). Also try to add a better background in that page.

**Comment by Code-Aditya-14** [comment]
Yeah Sure, go ahead :)
@Jsiddareddi-intuit

**Comment by Rashmisingh-18** [comment]
Hey @Code-Aditya-14, could you please assign this issue to me?

**Comment by Code-Aditya-14** [comment]
@Rashmisingh-18 I requested some changes in style-main page. You can do that and then I will approve your changes. Also if you want more such issue you may re-design the index page too.
